### PR TITLE
Version bump google cloud storage

### PR DESCRIPTION
**Pull request by grycyk**
Trying to solve issues #58 & #69

### CODE REVIEW

**Comment by grycyk** [comment]
@googlebot I signed it!

**Comment by grycyk** [comment]
@powerivq I see the version on master is v1.0.6 but only v1.0.5 is released, any chance we can get this PR merged and have a v1.0.6?

**Comment by spencer-hivert-ck** [comment]
@powerivq would love a release with this version bump in there as well!

**Comment by powerivq** [comment]
@joshdholtz can you add me back? can't push now.

**Comment by joshdholtz** [comment]
@powerivq I think you should be invited now! Did it through my phone so 🤷‍♂️

**Comment by powerivq** [comment]
@joshdholtz I did.

@spencer-hivert-ck That was done.

**Pull request merged**
